FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir git+https://github.com/dvsrepo/inspect_ai.git@fallback-to-modified-for-hf-fs huggingface_hub

EXPOSE 7860

CMD ["sh", "-c", "inspect view --log-dir \"${LOG_DIR}\" --host 0.0.0.0 --port 7860"]